apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: image-dashboard
spec:
  selector:
    matchLabels:
      app: image-dashboard
      tier: management
  replicas: 1
  template:
    metadata:
      labels:
        app: image-dashboard
        tier: management
    spec:
      containers:
      - name: master
        imagePullPolicy: Always
        image: gitcommit/k8s-image-dashboard
        resources:
          limits:
            memory: 200M
        ports:
        - containerPort: 3000
