apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: image-dashboard
spec:
  selector:
    matchLabels:
      app: image-dashboard
      tier: management
  replicas: 1
  template:
    metadata:
      labels:
        app: image-dashboard
        tier: management
    spec:
      containers:
      - name: image-dashboard
        image: gitcommit/k8s-image-dashboard:v1.0.3
        env:
         - name: REPO_REGEX
           value: gitcommit\/([a-zA-Z0-9-_]+):(.*)$|https://github.com/victorboissiere/$1/tree/$2
        resources:
          limits:
            memory: 200M
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 30
        ports:
        - containerPort: 3000
