apiVersion: v1
kind: Service
metadata:
  name: image-dashboard
  labels:
    app: image-dashboard
    tier: management
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: image-dashboard
    tier: management
  type: NodePort
